# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: 'public/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: tenant
    label: Tenant
    folder: content/tenants
    create: true
    delete: true
    extension: 'json'
    editor:
      preview: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Team Name
        name: teamName
        widget: string
      - label: Phone Number
        name: phoneNumber
        widget: string
      - label: Logo
        name: logo
        widget: image
      - label: Brand Color
        name: color
        widget: string

  - name: topic
    label: Topic
    folder: content/topics
    create: true
    extension: 'json'
    delete: true
    editor:
      preview: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Image
        name: image
        widget: image
      - label: Chapters
        name: chapters
        widget: list
        required: false
        fields:
          - label: Chapter
            name: chapter
            widget: relation
            collection: chapter
            searchFields: ['title', topic]
            valueField: title
            displayFields: ['topic', 'title']

  - name: chapter
    label: Chapter
    folder: content/chapters
    create: true
    extension: 'json'
    delete: true
    editor:
      preview: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Image
        name: image
        widget: image
      - label: Modules
        name: modules
        widget: list
        required: false
        fields:
          - label: Module
            name: module
            widget: relation
            collection: chapterModules
            searchFields:
              - title
            valueField: title
      - label: Topic
        name: topic
        widget: relation
        collection: topic
        required: true
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title']

  - name: chapterModules
    label: Module
    editor:
      preview: true
    folder: content/modules
    slug: '{{slug}}'
    create: true
    delete: true
    extension: 'json'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Image
        name: image
        widget: image

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - {
                  label: Twitter Site Account,
                  name: twitterSiteAccount,
                  widget: string,
                  required: false,
                }
              - {
                  label: Twitter Creator Account,
                  name: twitterCreatorAccount,
                  widget: string,
                  required: false,
                }
          - {
              label: Header Meta / Scripts,
              name: headerScripts,
              widget: text,
              required: false,
            }
          - {
              label: Enable Service Worker Pre-Cache,
              name: enableServiceWorker,
              widget: boolean,
              required: false,
            }
